apiVersion: v1
kind: ConfigMap
metadata:
  name: my-family-net-config
  namespace: my-family-net
data:
  ############################# Front-End #######################################
  VITE_APP_API_IP: http://api-gateway-svc.my-family-net.svc.cluster.local
  VITE_KEYCLOAK_URL: https://keycloakmyfamilynet.local.moglidev.xyz
  VITE_KEYCLOAK_REALM: my-family-net
  VITE_KEYCLOAK_CLIENT_ID: my-family-net-app
  ############################# Micro-Services ###################################
  REALM_NAME: my-family-net
  KEYCLOAK_HOST: https://keycloakmyfamilynet.local.moglidev.xyz
  SERVER_PORT_GATEWAY: "5000"
  SERVER_PORT_SOCIAL: "5002"
  DAPR_PORT_GATEWAY: "3500"
  DAPR_URL_GATEWAY: http://localhost:3500
  DAPR_PORT_SOCIAL: "3501"
  DAPR_URL_SOCIAL: http://localhost:3501
  APP_CORS_ORIGINS: http://40.0.0.83:3080
  NEO4J_HOST: neo4j://40.0.0.82:7687
  


