apiVersion: apps/v1
kind: Deployment
metadata:
  name: social
  namespace: my-family-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "social-service"
        dapr.io/app-port: "5002"
        dapr.io/sidecar-http-port: "3501"
    spec:
      containers:
      - name: social-service
        image: registry.moglidev.xyz/my-family-net-api-social-svc:1.0.0-JENKINS-14
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: SERVER_PORT_SOCIAL
          valueFrom:
            configMapKeyRef:
              name: my-family-net-config
              key: SERVER_PORT_SOCIAL
        - name: DAPR_PORT_SOCIAL
          valueFrom:
            configMapKeyRef:
              name: my-family-net-config
              key: DAPR_PORT_SOCIAL
        - name: KEYCLOAK_HOST
          valueFrom:
            configMapKeyRef:
              name: my-family-net-config
              key: KEYCLOAK_HOST
        - name: REALM_NAME
          valueFrom:
            configMapKeyRef:
              name: my-family-net-config
              key: REALM_NAME
        - name: NEO4J_HOST
          valueFrom:
            configMapKeyRef:
              name: my-family-net-config
              key: NEO4J_HOST
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: neo4j-myfamilynet-secret
              key: NEO4J_USER
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-myfamilynet-secret
              key: NEO4J_PASSWORD
        resources:
      imagePullSecrets:
      - name: registry-moglidev-xyz-secret
---
apiVersion: v1
kind: Service
metadata:
  name: social-svc
  namespace: my-family-net
spec:
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app: social